# Create Data

In [1]:
%%bash
python ./generate_data.py
python ./run_ddl.py

2026-02-17 10:25:39,678 - __main__ - INFO - Parsed command line arguments
2026-02-17 10:25:39,678 - __main__ - INFO - Starting TPC-H dataset generation pipeline
2026-02-17 10:25:39,678 - __main__ - INFO - Starting TPC-H table creation with scaling factor 0.1
2026-02-17 10:25:41,776 - __main__ - INFO - TPC-H tables created with scaling factor 0.1
2026-02-17 10:25:41,776 - __main__ - INFO - Starting export of TPC-H tables to csv format in ./data
2026-02-17 10:25:41,790 - __main__ - INFO - Found 8 tables to export
2026-02-17 10:25:41,790 - __main__ - INFO - Exporting customer to ./data/customer.csv
2026-02-17 10:25:41,825 - __main__ - INFO - Exported customer to ./data/customer.csv
2026-02-17 10:25:41,825 - __main__ - INFO - Exporting lineitem to ./data/lineitem.csv
2026-02-17 10:25:42,142 - __main__ - INFO - Exported lineitem to ./data/lineitem.csv
2026-02-17 10:25:42,142 - __main__ - INFO - Exporting nation to ./data/nation.csv
2026-02-17 10:25:42,145 - __main__ - INFO - Exported nation to ./data/nation.csv
2026-02-17 10:25:42,145 - __main__ - INFO - Exporting orders to ./data/orders.csv
2026-02-17 10:25:42,249 - __main__ - INFO - Exported orders to ./data/orders.csv
2026-02-17 10:25:42,250 - __main__ - INFO - Exporting part to ./data/part.csv
2026-02-17 10:25:42,267 - __main__ - INFO - Exported part to ./data/part.csv
2026-02-17 10:25:42,267 - __main__ - INFO - Exporting partsupp to ./data/partsupp.csv
2026-02-17 10:25:42,331 - __main__ - INFO - Exported partsupp to ./data/partsupp.csv
2026-02-17 10:25:42,331 - __main__ - INFO - Exporting region to ./data/region.csv
2026-02-17 10:25:42,338 - __main__ - INFO - Exported region to ./data/region.csv
2026-02-17 10:25:42,338 - __main__ - INFO - Exporting supplier to ./data/supplier.csv
2026-02-17 10:25:42,348 - __main__ - INFO - Exported supplier to ./data/supplier.csv
2026-02-17 10:25:42,348 - __main__ - INFO - All tables exported infofully to csv format
2026-02-17 10:25:42,348 - __main__ - INFO - TPC-H dataset with scaling factor 0.1 has been generated in ./data
WARNING: Using incubator modules: jdk.incubator.vector
26/02/17 10:25:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/02/17 10:25:44 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
2026-02-17 10:25:47,162 - __main__ - INFO - Dropping any existing TPCH tables
2026-02-17 10:25:47,282 - __main__ - INFO - Creating TPCH Iceberg tables
2026-02-17 10:25:47,673 - __main__ - INFO - Loading data into TPCH Iceberg tables
2026-02-17 10:25:47,673 - __main__ - INFO - Reading customer data from /home/airflow/notebooks/data/customer.csv
2026-02-17 10:25:49,905 - __main__ - INFO - Reading lineitem data from /home/airflow/notebooks/data/lineitem.csv
2026-02-17 10:25:54,851 - __main__ - INFO - Reading nation data from /home/airflow/notebooks/data/nation.csv
2026-02-17 10:25:55,163 - __main__ - INFO - Reading orders data from /home/airflow/notebooks/data/orders.csv
2026-02-17 10:25:56,065 - __main__ - INFO - Reading part data from /home/airflow/notebooks/data/part.csv
2026-02-17 10:25:56,452 - __main__ - INFO - Reading partsupp data from /home/airflow/notebooks/data/partsupp.csv
2026-02-17 10:25:56,994 - __main__ - INFO - Reading region data from /home/airflow/notebooks/data/region.csv
2026-02-17 10:25:57,263 - __main__ - INFO - Reading supplier data from /home/airflow/notebooks/data/supplier.csv
2026-02-17 10:25:57,539 - py4j.clientserver - INFO - Closing down clientserver connection

Run Python code as shown below

In [2]:
a = 10

Run SQL code as shown below, with the `%%sql` called magics

In [3]:
%%sql
select 1

   1
0  1

We use the `prod.db` schema where all our tables are create by `run_ddl.py`

In [4]:
%%sql 
use prod_db

Empty DataFrame
Columns: []
Index: []

## Your code below

In [ ]:
%%sql 
WITH orders_cte AS (
    SELECT
        o_orderkey,
        o_custkey,
        o_orderstatus,
        CAST(o_orderdate AS TIMESTAMP) AS o_orderdate,
        o_orderpriority,
        o_clerk,
        o_shippriority,
        o_comment,
        o_totalprice
    FROM orders
),
stg_customers AS (
    SELECT
        c_custkey,
        c_name,
        c_address,
        c_nationkey,
        c_phone,
        c_acctbal,
        c_mktsegment,
        c_comment
    FROM customer
),
nation_cte AS (
    SELECT
        CAST(n_nationkey AS INT) AS n_nationkey,
        CAST(n_name AS STRING) AS n_name,
        CAST(n_regionkey AS INT) AS n_regionkey,
        CAST(n_comment AS STRING) AS n_comment
    FROM nation
),
dim_customers AS (
    SELECT
        c.c_custkey,
        c.c_name,
        c.c_address,
        c.c_nationkey,
        n.n_name AS nation_name,
        c.c_phone,
        c.c_acctbal,
        c.c_mktsegment,
        c.c_comment
    FROM stg_customers c
    INNER JOIN nation_cte n ON c.c_nationkey = n.n_nationkey
)
SELECT
    o.o_orderkey,
    o.o_custkey,
    o.o_orderstatus,
    o.o_orderdate,
    o.o_orderpriority,
    o.o_clerk,
    o.o_shippriority,
    o.o_totalprice,
    c.c_name AS customer_name,
    c.c_address AS customer_address,
    c.c_phone AS customer_phone,
    c.c_acctbal AS customer_account_balance,
    c.c_mktsegment AS customer_market_segment,
    c.nation_name AS customer_nation_name
FROM orders_cte o
INNER JOIN dim_customers c ON o.o_custkey = c.c_custkey;